services:
  - type: worker
    name: tennis-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python tennis_arbitrage_telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9